services:
  bimrocket-webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    image: bimrocket-webapp
    container_name: bimrocket-webapp
    restart: always
    environment:
      - BIMROCKET_ENV=/root/bimrocket/js/Environment.js
    ports:
      - "8181:8080"
    volumes:
      - ./Environment.js:/root/bimrocket/js/Environment.js
    networks:
      - bimrocket_network

networks:
  bimrocket_network:
    driver: bridge